#pragma once
#include <vector>
#include <string>

// Extracted from example_input.ini
static const std::vector<std::string> mapping_keys = {
    "Flight_Gun",
    "Flight_Missile",
    "Flight_Weapon",
    "Flight_Target",
    "Flight_Radar",
    "Flight_Flare",
    "Flight_View",
    "Flight_AccelerationDeceleration",
    "Flight_AutoPilot",
    "Flight_Pause",
    "Flight_HatSwitchUp",
    "Flight_HatSwitchDown",
    "Flight_HatSwitchLeft",
    "Flight_HatSwitchRight",
    "Flight_Pitch",
    "Flight_Roll",
    "Flight_Yaw",
    "Flight_Throttle",
    "Flight_CameraPitch",
    "Flight_CameraYaw",
    "UI_B",
    "UI_A",
    "UI_X",
    "UI_Y",
    "UI_LeftStickPress",
    "UI_RightStickPress",
    "UI_DPadUp",
    "UI_DPadDown",
    "UI_DPadLeft",
    "UI_DPadRight",
    "UI_LeftStickUp",
    "UI_LeftStickDown",
    "UI_LeftStickLeft",
    "UI_LeftStickRight",
    "UI_Menu",
    "UI_LB",
    "UI_RB",
    "UI_LT",
    "UI_RT",
    "UI_RightStickUp",
    "UI_RightStickDown",
    "UI_RightStickLeft",
    "UI_RightStickRight"
};
